tasks:
  - init: |
      # Install pyenv if it's not already installed
      if ! command -v pyenv &> /dev/null
      then
        curl https://pyenv.run | bash
      fi
      
      # Set up pyenv environment
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)"
      
      # Install Python 3.11.9 and set it as the global default
      pyenv install 3.11.9
      pyenv global 3.11.9
      
      # Verify installation
      python --version
      source .venv/bin/activate
      cd ml-modeling-pipeline/
